include:
  - project: hpc/gitlab-pipelines
    file:
    - spack-build.gitlab-ci.yml
  - project: nse/ci
    file:
    - /ci/lib/tox-bb5.yml
    - /ci/jobs/docs.yml
    - ci/jobs/lint.yml
    - /ci/jobs/publish-docs.yml

workflow:
  rules:
  - if: $CI_PIPELINE_SOURCE == "schedule"
  - if: $CI_PIPELINE_SOURCE == "web"
  - if: "$CI_MERGE_REQUEST_IID"
  - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
  - if: $CI_COMMIT_TAG

stages:
- .pre
- build
- test
- publish

variables:
  SPACK_PACKAGE: py-multiscale-run
  SPACK_PACKAGE_DEPENDENCIES: ^hdf5~cxx

.tox-template:
  tags: [bb5_map]
  variables:
    EXTRA_MODULES:
      unstable:gcc
      unstable:git
      unstable:gmsh
      unstable:hpe-mpi
      unstable:julia
      unstable:neurodamus-neocortex-multiscale
      unstable:petsc
      unstable:py-libsonata
      unstable:py-mpi4py
      unstable:py-notebook
      unstable:py-numpy
      unstable:py-petsc4py
      unstable:py-scipy
      unstable:steps

pytest:
  extends: .spack_test
  script:
  # Tell Git how to re-write BBP GitLab URLs to use a token instead of SSH
  - !reference [.bbp_gitlab_access, script]
  - !reference [.spack_test, script]

integration:
  extends: .spack_test
  timeout: 10 minutes
  variables:
    bb5_duration: "00:10:00"
    bb5_ntasks: 2

.nrun_test:
  extends: .spack_test
  timeout: 3 hours
  artifacts:
    when: always
    paths:
    - msr-sim-$CI_JOB_NAME_SLUG/RESULTS/*
    expire_in: 4 hours
  variables:
    bb5_memory: 64G
    bb5_ntasks: 32
    bb5_duration: "03:00:00"
  script:
  - spack ${SPACK_EXTRA_FLAGS} load /${SPACK_INSTALLED_HASH}
  - ${SPACK_SOURCE_DIR}/.ci/test_simulation.sh

.dualrun_test:
  extends: .nrun_test
  timeout: 2 hours
  variables:
    steps: "true"
    metabolism: "false"
    bloodflow: "false"

dualrun_test 1/16:
  extends: .dualrun_test
  variables:
    bb5_ntasks: 1
    bb5_duration: "02:00:00"
    tstop: 105

dualrun_test 2/16:
  extends: .dualrun_test
  variables:
    bb5_ntasks: 2
    tstop: 105

dualrun_test 16/16:
  extends: .dualrun_test
  variables:
    bb5_ntasks: 16
    tstop: 1000

nrun_[steps, metab, bf]:
  extends: .nrun_test
  variables:
    tstop: 500
  parallel:
    matrix:
    - steps: ["false", "true"]
      metabolism: ["false", "true"]
      bloodflow: ["false", "true"]

init_julia_create_test:
  extends: .spack_test
  timeout: 1 hours
  when: manual
  variables:
    bb5_duration: "01:00:00"
    bb5_ntasks: 2
  script:
  - spack ${SPACK_EXTRA_FLAGS} load /${SPACK_INSTALLED_HASH}
  - ${SPACK_SOURCE_DIR}/.ci/test_init_julia_create.sh

publish-docs:
  tags: []
  needs: [docs]
  rules:
  - if: $CI_COMMIT_TAG
  image: quay.io/pypa/manylinux2014_x86_64

lint:
  stage: .pre
