include:
  - project: hpc/gitlab-pipelines
    file: 
      - spack-build-components.gitlab-ci.yml
      - bbp-gitlab-access.yml

default:
  tags: [bb5_map]

variables:
  STEPS_BRANCH:
    value: master
  NEURODAMUS_NEOCORTEX_BRANCH:
    value: main

spack_setup:
  extends: .spack_setup_ccache

.build:
  extends: [.spack_build]
  variables:
    bb5_ntasks: 2   # so we block 16 cores
    bb5_cpus_per_task: 8 # ninja -j {this}
    bb5_memory: 76G # ~16*384/80

steps_setup:
  extends: [.build]
  variables:
    SPACK_PACKAGE: steps
    SPACK_PACKAGE_SPEC: +distmesh+petsc

neurodamus_setup:
  extends: [.build]
  variables:
    SPACK_PACKAGE: neurodamus-neocortex
    SPACK_PACKAGE_SPEC: +ngv+metabolism

.allocation:
  variables:
    bb5_exclusive: "full"
    bb5_constraint: cpu
    bb5_memory: 0
    bb5_cpus_per_task: 2
    OMP_NUM_THREADS: 1

pytests:
  extends: .allocation
  stage: test
  needs:
    - steps_setup
    - neurodamus_setup
  script:
    - !reference [.bbp_gitlab_access, script]
    - . ${SPACK_ROOT}/share/spack/setup-env.sh
    - source setup.sh
    - pytest pytests

.nrun_test:
  extends: .allocation
  timeout: 2 hours
  stage: test
  needs:
    - steps_setup
    - neurodamus_setup
  artifacts:
    when: always
    paths:
      - RESULTS/*
    expire_in: 5 days
  variables:
    blueconfig_path: BlueConfig
    mesh_path: steps_meshes/mc2c/mc2c.msh
    #leave it empty (master) or add your favorite branch that you want to check
    steps_branch: master
  script:
    - !reference [.bbp_gitlab_access, script]
    - . ${SPACK_ROOT}/share/spack/setup-env.sh
    - source setup.sh $custom_HBP_STEPS
    - .ci/test.sh

dualrun_test:
  extends: .nrun_test
  timeout: 2 hours
  variables:
    bb5_duration: "01:00:00"
    bb5_ntasks: 16
    nrun: 2

triplerun_test:
  extends: .nrun_test
  timeout: 2 hours
  variables:
    bb5_duration: "02:00:00"
    bb5_ntasks: 32
    nrun: 3



