include:
  - project: hpc/gitlab-pipelines
    file: 
      - spack-build-components.gitlab-ci.yml

default:
  tags: [bb5_map]

variables:
  STEPS_BRANCH:
    value: master
  NEURODAMUS_NEOCORTEX_BRANCH:
    value: main


.build:
  extends: [.spack_build]
  variables:
    bb5_ntasks: 2   # so we block 16 cores
    bb5_cpus_per_task: 8 # ninja -j {this}
    bb5_memory: 76G # ~16*384/80

.steps_setup:
  extends: [.build]
  variables:
    SPACK_PACKAGE: steps
    SPACK_PACKAGE_SPEC: +distmesh+petsc

.neurodamus_setup:
  extends: [.build]
  variables:
    SPACK_PACKAGE: neurodamus-neocortex
    SPACK_PACKAGE_SPEC: +ngv

dualrun_test:
  variables:
    bb5_exclusive: "full"
    bb5_duration: "01:00:00"
    bb5_constraint: cpu
    bb5_ntasks: 16
    bb5_cpus_per_task: 1
  script:
    - .ci/test_dualrun.sh
