include:
  - project: hpc/gitlab-pipelines
    file: 
      - spack-build-components.gitlab-ci.yml

default:
  tags: [bb5_map]

variables:
  STEPS_BRANCH:
    value: master
  NEURODAMUS_NEOCORTEX_BRANCH:
    value: main

spack_setup:
  extends: .spack_setup_ccache

.build:
  extends: [.spack_build]
  variables:
    bb5_ntasks: 2   # so we block 16 cores
    bb5_cpus_per_task: 8 # ninja -j {this}
    bb5_memory: 76G # ~16*384/80

steps_setup:
  extends: [.build]
  variables:
    SPACK_PACKAGE: steps
    SPACK_PACKAGE_SPEC: +distmesh+petsc

neurodamus_setup:
  extends: [.build]
  variables:
    SPACK_PACKAGE: neurodamus-neocortex
    SPACK_PACKAGE_SPEC: +ngv

.allocation:
  variables:
    bb5_exclusive: "full"
    bb5_constraint: cpu
    bb5_memory: 0
    bb5_cpus_per_task: 2

dualrun_test:
  extends: [.allocation]
  stage: test
  needs:
    - steps_setup
    - neurodamus_setup
  variables:
    bb5_duration: "01:00:00"
    bb5_ntasks: 16
  script:
    - . ${SPACK_ROOT}/share/spack/setup-env.sh
    - .ci/test_dualrun.sh

triplerun_test:
  extends: [.allocation]
  artifacts:
    when: always
    paths: 
      - RESULTS/*
    expire_in: 4 weeks
  stage: test
  needs:
    - steps_setup
    - neurodamus_setup
  variables:
    bb5_duration: "02:00:00"
    bb5_ntasks: 32
  script:
    - . ${SPACK_ROOT}/share/spack/setup-env.sh
    - .ci/test_triplerun.sh
