include:
  - project: hpc/gitlab-pipelines
    file:
    - github-project-pipelines.gitlab-ci.yml
    - spack-build.gitlab-ci.yml

workflow:
  rules:
  - if: $CI_PIPELINE_SOURCE == "schedule"
  - if: $CI_PIPELINE_SOURCE == "web"
  - if: "$CI_EXTERNAL_PULL_REQUEST_IID"
  - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
  - if: $CI_COMMIT_TAG

default:
  tags: [bb5_map]

stages:
- build

variables:
  SPACK_PACKAGE: py-multiscale-run
