#!/bin/bash

#SBATCH --job-name="NGV"
#SBATCH --nodes=8
#SBATCH --ntasks-per-node=32

#SBATCH --account=proj40
#SBATCH --partition=prod
#SBATCH --constraint=cpu
#SBATCH --time=01:00:00

#SBATCH --cpus-per-task=2
#SBATCH --exclusive
#SBATCH --mem=0
#SBATCH --output="%x-%j.log"

# with a random arg we avoid the complete reinstallation of the various packages
source ./set_env.sh 12

# driver script
PYDRIVER=multiscale_run_STEPS3.py
export which_STEPS=3
export which_mesh=cubeBB
# Like in C, the integers 0 (false) and 1 (true—in fact any nonzero integer) are used.
export dualrun=1
export triplerun=1
echo " *** STEPS${which_STEPS} run *** "
time srun dplace x86_64/special -mpi -python ${PYDRIVER}
