#!/bin/bash

#SBATCH --job-name="multiscale_run"
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=32

#SBATCH --account=proj40
#SBATCH --partition=prod
#SBATCH --constraint=cpu
#SBATCH --time=02:00:00

#SBATCH --cpus-per-task=2
#SBATCH --exclusive
#SBATCH --mem=0
#SBATCH --output="%x-%j.log"



# add your favourite steps branch or leave it empty for master
#export steps_branch=master

source ./setup.sh

steps_version=3
mesh_path=steps_meshes/mc2c/mc2c.msh
blueconfig_path=BlueConfig
nrun=2
RESULTS_PATH=RESULTS/STEPS$steps_version

echo " *** STEPS${steps_version} run *** "
time srun dplace special -mpi -python main.py $nrun $steps_version $RESULTS_PATH $blueconfig_path $mesh_path
