name: Publish wheel and source distributions to PyPI
on:
  push:
    tags:
    - '*'

jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
    - name: Build source distribution
      run: |
        python -m pip install build
        python -m build
    - name: Store them as artifact
      uses: actions/upload-artifact@v4
      with:
        name: sdist
        path: dist/*.tar.gz

  build_wheel:
    name: Build wheel
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
    - name: Build distributions
      run: |
        python -m pip install build
        python -m build --wheel
    - name: Store them as artifact
      uses: actions/upload-artifact@v4
      with:
        name: wheel
        path: dist/*.whl


  publish:
    name: Publish distributions to PyPI
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    needs:
    - build_sdist
    - build_wheel
    environment:
      name: publish_pypi
      url: https://pypi.org/p/multiscale-run
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    - name: Download artifacts produced by the build_sdist job
      uses: actions/download-artifact@v4
      with:
        name: sdist
        path: dist/
    - name: Download artifacts produced by the build_wheel job
      uses: actions/download-artifact@v4
      with:
        name: wheel
        path: dist/
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: dist
    - name: Publish packages to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages_dir: dist/
