name: Test the contribution
on:
  pull_request:
  push:
    branches:
    - main
env:
  apt_options: -o Acquire::Retries=3
  apt_pkgs: >
    build-essential git libgl1 libglu1 libopenblas-dev libopenmpi-dev
    librdmacm-dev libxcursor1 libxft2 libxinerama1
    libxrender1 zlib1g-dev
  PYTHON_VERSION: "3.11"
jobs:
  test:
    name: Build and test the contribution
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Setup MPI
      uses: mpi4py/setup-mpi@v1
      with:
        mpi: openmpi

    - name: Setup Julia
      uses: julia-actions/setup-julia@v2
      with:
        version: '1.9.3'

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install system packages for MPI and STEPS requirements
      run: |
        sudo apt-get ${{ env.apt_options }} update -y
        sudo apt-get ${{ env.apt_options }} install ${{ env.apt_pkgs }}
    - name: Upgrade Python core packages
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install tox-gh-actions

    - name: Prepare tox environment
      run: |
        tox run --notest -e py${{ env.PYTHON_VERSION }}
    - name: Run tox
      run: |
        tox -e py${{ env.PYTHON_VERSION }}
